Repository Assembless/circles-web, pull requests merged in 2021-02, with the labels that each got.

#68 Add profile styling
  src/api/hooks.ts
  src/api/models/Account.model.ts
  src/components/common/TopMenu/MenuPopover/index.tsx
  src/components/pages/Home/styles.ts
  src/components/pages/Login/index.tsx
  src/components/pages/Profile/index.tsx
  src/components/pages/Profile/styles.ts
  src/components/pages/Profile/trans.ts
  src/components/pages/Splash/index.tsx
  src/components/pages/Welcome/index.tsx
  src/store/context.ts
Labels: enhancement

#73 ✏️ Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#71 :bug: Fix AccountPicker bug
  src/components/common/AccountPicker/index.tsx
Labels: bug

#76 Add friends view
  package.json
  src/api/models/Account.model.ts
  src/components/common/TopMenu/index.tsx
  src/components/pages/Highlights/index.tsx
  src/components/pages/Highlights/trans.ts
  src/components/pages/Home/index.tsx
  src/components/pages/Home/styles.ts
  src/components/pages/Menu/index.tsx
  src/components/pages/Menu/styles.ts
  src/components/pages/People/ContactLabel.tsx
  src/components/pages/People/index.tsx
  src/components/pages/People/styles.ts
  src/components/pages/Room/RoomView.tsx
  src/components/pages/Rooms/CreateRoom.tsx
  src/components/pages/Rooms/RoomsItem.tsx
  src/components/pages/Rooms/index.tsx
  src/components/pages/Rooms/styles.ts
  src/components/shared/FloatingList/index.tsx
  src/components/shared/FloatingList/styles.ts
  yarn.lock
Labels: enhancement
